### PR TITLE
Fix AppBundle namespace issue

### PR DESCRIPTION
**Pull request by terox**
Hello again,

Seems that 2.1 tag is broken. There are some issue with namespaces.

This are not detected by tests because they are not tested.

This will fix it.

Thank you

### CODE REVIEW

**Comment by terox** [comment]
I am observing that are a little issues with CompilerPass also. I will try to investigate later. I think that we will need create another PR because it isn't related with that.

**Comment by terox** [comment]
Ok my last message is related with old configuration, but nothing to worry.

This PR will fix the namespace issues.

Thank you

**Comment by Brunty** [comment]
@leightonthomas can you double check this?

**Comment by terox** [comment]
Hello,

Could be merged and tagged?

Thank you ;)

**Comment by Brunty** [comment]
@terox done, thanks! (apologies for the delay) :)

**Pull request merged**
